import os
from dataclasses import dataclass

def _b(name, default=False): return os.getenv(name, str(default)).lower() in {'1','true','yes','on'}
def _i(name, default): return int(os.getenv(name, str(default)))
def _f(name, default): return float(os.getenv(name, str(default)))

@dataclass(frozen=True)
class Settings:
    app_env: str=os.getenv('APP_ENV','production')
    live_trading: bool=_b('LIVE_TRADING',False)
    auto_trading_enabled: bool=_b('AUTO_TRADING_ENABLED',False)
    require_human_approval_auto: bool=_b('REQUIRE_HUMAN_APPROVAL_AUTO',True)
    live_production_ack: str=os.getenv('LIVE_PRODUCTION_ACK','')
    operator_api_token: str=os.getenv('OPERATOR_API_TOKEN','')
    require_operator_auth: bool=_b('REQUIRE_OPERATOR_AUTH',True)
    database_url: str=os.getenv('DATABASE_URL','postgresql+psycopg://iort:iort@postgres:5432/iort')
    redis_url: str=os.getenv('REDIS_URL','redis://redis:6379/0')
    require_durable_event_bus: bool=_b('REQUIRE_DURABLE_EVENT_BUS',True)
    require_margin_evidence: bool=_b('REQUIRE_MARGIN_EVIDENCE',True)
    require_instrument_master: bool=_b('REQUIRE_INSTRUMENT_MASTER',True)
    data_stale_ms: int=_i('DATA_STALE_MS',1500)
    max_margin_utilization_pct: float=_f('MAX_MARGIN_UTILIZATION_PCT',70)
    max_net_exposure: float=_f('MAX_NET_EXPOSURE',1000000)
    max_daily_loss: float=_f('MAX_DAILY_LOSS',4000)
    portfolio_soft_sl: float=_f('PORTFOLIO_SOFT_SL',2000)
    portfolio_hard_sl: float=_f('PORTFOLIO_HARD_SL',4000)
    max_position_qty: int=_i('MAX_POSITION_QTY',1000)
    max_order_value: float=_f('MAX_ORDER_VALUE',500000)
    max_slippage_bps: float=_f('MAX_SLIPPAGE_BPS',50)
    watchdog_timeout_sec: int=_i('WATCHDOG_TIMEOUT_SEC',5)
    order_reconcile_interval_sec: int=_i('ORDER_RECONCILE_INTERVAL_SEC',2)
    require_authoritative_daily_pnl: bool=_b('REQUIRE_AUTHORITATIVE_DAILY_PNL',True)
    require_live_ltp_for_exposure: bool=_b('REQUIRE_LIVE_LTP_FOR_EXPOSURE',True)
    emergency_flatten_enabled: bool=_b('EMERGENCY_FLATTEN_ENABLED',True)
    smart_routing_enabled: bool=_b('SMART_ROUTING_ENABLED',True)
    routing_brokers: str=os.getenv('ROUTING_BROKERS','ZERODHA,KOTAK,UPSTOX,ANGEL')
    require_scenario_risk: bool=_b('REQUIRE_SCENARIO_RISK',False)
    max_scenario_loss: float=_f('MAX_SCENARIO_LOSS',1000000)
    max_abs_delta: float=_f('MAX_ABS_DELTA',1000000)
    max_abs_vega: float=_f('MAX_ABS_VEGA',1000000)
    audit_chain_required: bool=_b('AUDIT_CHAIN_REQUIRED',True)
    subscription_json: str=os.getenv('SUBSCRIPTION_JSON','{}')
    instrument_master_urls_json: str=os.getenv('INSTRUMENT_MASTER_URLS_JSON','{}')
    zerodha_api_key: str=os.getenv('ZERODHA_API_KEY',''); zerodha_access_token: str=os.getenv('ZERODHA_ACCESS_TOKEN','')
    upstox_access_token: str=os.getenv('UPSTOX_ACCESS_TOKEN','')
    angel_api_key: str=os.getenv('ANGEL_API_KEY',''); angel_access_token: str=os.getenv('ANGEL_ACCESS_TOKEN',''); angel_client_code: str=os.getenv('ANGEL_CLIENT_CODE',''); angel_feed_token: str=os.getenv('ANGEL_FEED_TOKEN','')
    kotak_api_key: str=os.getenv('KOTAK_API_KEY',''); kotak_mobile: str=os.getenv('KOTAK_MOBILE',''); kotak_client_code: str=os.getenv('KOTAK_CLIENT_CODE',''); kotak_totp: str=os.getenv('KOTAK_TOTP',''); kotak_mpin: str=os.getenv('KOTAK_MPIN','')
settings=Settings()
