"use strict";
// Core: helpers, tabs, dashboard rendering, event stream and operator controls.
const TABS=[['overview','Overview'],['market','Market'],['chain','Option Chain'],['portfolio','Portfolio'],['strategy','Strategy'],['risk','Risk'],['controls','Controls'],['execution','Execution'],['orders','Orders'],['recon','Reconciliation'],['tca','TCA'],['system','System']];
let ws=null,reconnectTimer=null,lastOk=0,refreshing=false,wsLastMsg=0,wsDelay=500;
// fetch with a timeout: a hung backend can never leave a view frozen on old numbers.
async function fetchT(url,opts={},ms=2500){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);try{return await fetch(url,Object.assign({cache:'no-store'},opts,{signal:ac.signal}))}finally{clearTimeout(tm)}}const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const cls=(el,c)=>{el.className=el.className.replace(/\b(ok|bad|warn)\b/g,'').trim()+' '+c};
function initTabs(){TABS.forEach(([id,label],i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.tab=id;b.setAttribute('role','tab');b.setAttribute('aria-controls',id);b.title=i<9?`${label} (Alt+${i+1})`:label;b.onclick=()=>showTab(id);$('tabs').appendChild(b)});
 let start=(location.hash||'').slice(1);if(!TABS.some(t=>t[0]===start)){try{start=localStorage.getItem('iort.tab')||''}catch{start=''}}
 showTab(TABS.some(t=>t[0]===start)?start:TABS[0][0])}
function showTab(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>{x.classList.toggle('active',x.dataset.tab===id);x.setAttribute('aria-selected',x.dataset.tab===id)});
 try{localStorage.setItem('iort.tab',id)}catch{}if(location.hash!=='#'+id)history.replaceState(null,'','#'+id);
 CH.active=id==='chain';if(CH.active){CH.scroll=true;chLoadIndex().then(chLoadLadder)}
 window.dispatchEvent(new CustomEvent('iort:tab',{detail:id}))}
function logEvent(target,e){const el=$(target);if(!el)return;const row=document.createElement('div');row.className='event';row.textContent=new Date().toLocaleTimeString()+'  '+(e.type||'EVENT')+'  '+JSON.stringify(e.payload||e);el.prepend(row);while(el.children.length>100)el.removeChild(el.lastChild)}
const yn=v=>v?'<span class="ok">YES</span>':'<span class="bad">NO</span>';
const metric=(k,v,c='')=>`<div class="metric"><span>${esc(k)}</span><b class="${c}">${esc(v)}</b></div>`;
let LAST={};
const FEED_CLS={CONNECTED:'ok',CONNECTING:'warn',RECONNECTING:'warn',IDLE:'',PAUSED:'bad',LOGIN_HALTED:'bad',STOPPED:'bad'};
const dur=s=>s==null?'—':s<90?`${Math.round(s)} s`:s<5400?`${Math.round(s/60)} min`:`${(s/3600).toFixed(1)} h`;
function feedLabel(w){const st=w.state||'IDLE';if(st==='RECONNECTING')return`RECONNECTING${w.attempt?` (${w.attempt})`:''}${w.next_retry_in?` · ${dur(w.next_retry_in)}`:''}`;if(st==='IDLE')return'WAITING FOR TOKENS';if(st==='PAUSED')return'DOWN · AUTO OFF';return st.replace('_',' ')}
const feedBtns=w=>`<button class="action" type="button" data-action="reconnect" data-broker="${esc(w.broker)}">Reconnect now</button> <button class="linkbtn" type="button" data-action="auto-reconnect" data-broker="${esc(w.broker)}" data-on="${w.auto_reconnect?'false':'true'}" aria-pressed="${w.auto_reconnect?'true':'false'}">Auto: ${w.auto_reconnect?'ON':'OFF'}</button>`;
// The connection pill reflects both channels: the 3 s state poll and the live event stream.
function connPill(){const up=ws&&ws.readyState===1;$('conn').textContent=up?'EVENT STREAM':'API ONLY · EVENTS RECONNECTING';cls($('conn'),up?'ok':'warn')}
const istTime=v=>{const d=new Date(v);return isNaN(d)?'—':d.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false})};
function render(s){LAST=s;const sys=s.system||{};$('ver').textContent='v'+(s.version||'');
 const wk=sys.workers||[],byB=Object.fromEntries(wk.map(w=>[w.broker,w]));
 const worst=wk.find(w=>w.state!=='CONNECTED')||wk[0];$('streamPill').textContent=worst?`${worst.broker} ${feedLabel(worst)}`:'FEED NOT CONFIGURED';cls($('streamPill'),worst?FEED_CLS[worst.state]??'':'bad');
 const live=sys.market==='LIVE';$('ovMarket').textContent=sys.market||'DATA_UNAVAILABLE';cls($('ovMarket'),live?'ok':'bad');$('marketPill').textContent=sys.market||'DATA_UNAVAILABLE';cls($('marketPill'),live?'ok':'bad');
 $('ovExec').textContent=sys.live_trading?'LIVE':'LOCKED';cls($('ovExec'),sys.live_trading?'warn':'');$('modePill').textContent=sys.live_trading?'ORDERS LIVE':'ORDERS LOCKED';cls($('modePill'),sys.live_trading?'warn':'');
 const k=sys.kill||{};$('killPill').textContent='KILL: '+(k.active?'ON':'OFF');cls($('killPill'),k.active?'bad':'ok');$('riskKill').textContent=k.active?'ACTIVE':'OFF';cls($('riskKill'),k.active?'bad':'ok');$('riskKillWhy').textContent=k.reason?`${k.reason} · ${k.actor||''} · ${k.at||''}`:'';
 connPill();
 // Firm P&L only from fresh snapshots of every configured broker: a partial or empty sum is not a firm total.
 const agg=(s.risk||{}).aggregate||{},aggOk=!!agg.complete&&(agg.usable??(agg.brokers||[]).length)>0;$('ovPnl').textContent=aggOk?`${fmt(agg.total_pnl)} / ${fmt(agg.day_pnl)}`:'—';cls($('ovPnl'),aggOk?(agg.total_pnl<0?'bad':'ok'):'');$('ovPnl').title=aggOk?'':'No live broker data for every configured broker';
 // Readiness is about live order routing: while routing is locked it is not "READY", it is LOCKED.
 const rd=s.readiness||{};if(!sys.live_trading){$('ovReadyFlag').textContent='LOCKED';cls($('ovReadyFlag'),'');$('ovReady').textContent='Order routing is locked (LIVE_TRADING=false): every order is refused before any broker.'+((rd.reasons||[]).length?'\n'+rd.reasons.join('\n'):'')}
 else{$('ovReadyFlag').textContent=rd.ready?'READY':'BLOCKED';cls($('ovReadyFlag'),rd.ready?'ok':'bad');$('ovReady').textContent=(rd.reasons||[]).join('\n')||'none'}
 const bShown=(s.brokers||[]).filter(b=>b.status!=='UNCONFIGURED'),bOff=(s.brokers||[]).filter(b=>b.status==='UNCONFIGURED').map(b=>b.broker);
 $('ovBrokers').innerHTML=bShown.map(b=>metric(b.broker,b.status||'UNKNOWN',b.status==='LIVE'?'ok':['LOGGING_IN','NOT_LOGGED_IN'].includes(b.status)?'warn':'bad')
  +(b.error?`<div class="muted bad">${esc(b.error)}</div>`:'')+(byB[b.broker]?metric(b.broker+' feed',feedLabel(byB[b.broker]),FEED_CLS[byB[b.broker].state]??'')+`<div class="control" style="margin:4px 0 8px">${feedBtns(byB[b.broker])}</div>`:'')+(b.status==='LOGIN_HALTED'?`<div class="control" style="margin:6px 0"><button class="action amber" data-action="login-reset" data-broker="${esc(b.broker)}">Reset ${esc(b.broker)} login</button><span class="muted">Fix the credentials first. Needs the operator token from the Execution tab.</span></div>`:'')).join('')+(bOff.length?`<div class="muted" style="margin-top:6px">Not configured: ${esc(bOff.join(', '))}</div>`:'')||'<span class="muted">No broker data</span>';
 $('excRows').innerHTML=(s.exceptions||[]).map(o=>`<tr><td>${esc(o.client_order_id)}</td><td>${esc(o.broker)}</td><td>${esc(o.symbol)}</td><td>${esc(o.side)}</td><td>${esc(o.qty)}</td><td class="bad">${esc(o.status)}</td><td>${esc(o.last_reason)}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">None</td></tr>';
 const pos=v=>v>0?esc(v):'—',liveTicks=(s.market?.last_ticks||[]).filter(t=>!t.stale);
 $('marketRows').innerHTML=liveTicks.map(t=>`<tr><td>${esc(t.broker)}</td><td>${esc(t.instrument_token)}</td><td>${esc(t.exchange)}</td><td>${esc(t.symbol)}</td><td>${pos(t.ltp)}</td><td>${pos(t.bid)}</td><td>${pos(t.ask)}</td><td>${pos(t.oi)}</td><td>${t.exchange_ts_ms?esc(istTime(t.exchange_ts_ms)):'—'}</td></tr>`).join('')||`<tr><td colspan="9" class="muted">No live ticks.${(s.market?.last_ticks||[]).length?' Every last quote is older than '+esc(s.market?.stats?.data_stale_ms??'')+' ms, so none is shown.':''}</td></tr>`;
 const st=s.market?.stats||{};$('marketQuality').innerHTML=metric('Accepted ticks',st.accepted??0)+Object.entries(st.rejected_by_reason||{}).map(([r,n])=>metric('Rejected: '+r,n,'warn')).join('')+metric('Live brokers',(st.live_brokers||[]).join(', ')||'none');
 $('workerRows').innerHTML=wk.map(w=>`<tr><td><b>${esc(w.broker)}</b></td><td><span class="badge ${FEED_CLS[w.state]??''}">${esc(feedLabel(w))}</span></td><td>${w.state==='CONNECTED'?'up '+esc(dur(w.uptime_sec)):w.downtime_sec!=null?'<span class="bad">down '+esc(dur(w.downtime_sec))+'</span>':'—'}</td><td>${w.last_message_age_sec!=null?esc(dur(w.last_message_age_sec))+' ago':'—'}</td><td>${esc(w.reconnects)}</td><td>${esc(w.failures??0)}</td><td>${esc(w.dropped)}</td><td>${esc(w.dynamic_tokens??0)}</td><td class="wrap ${w.state!=='CONNECTED'&&w.last_error?'bad':'muted'}">${esc(w.state!=='CONNECTED'&&w.last_error?w.last_error:w.last_disconnect_reason?w.last_disconnect_reason+' · '+new Date(w.last_disconnect_at*1000).toLocaleTimeString():'—')}</td><td class="nowrap">${feedBtns(w)}</td></tr>`).join('')||'<tr><td colspan="10" class="muted">No live feed: no broker feed is configured.</td></tr>';
 $('chainRows').innerHTML=(s.option_chain?.chains||[]).slice().sort((a,b)=>(a.underlying+a.expiry).localeCompare(b.underlying+b.expiry)).map(c=>`<tr><td>${esc(c.exchange)}</td><td><b>${esc(c.underlying)}</b></td><td>${esc(c.expiry)}</td><td>${c.live_rows==null?esc(c.rows):c.live_rows?`${esc(c.live_rows)} live`:'<span class="warn">no live quote</span>'}</td><td><button class="linkbtn" type="button" data-action="open-chain" data-sym="${esc(c.exchange+'|'+c.underlying)}" data-exp="${esc(c.expiry)}">Open chain</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No option ticks yet.</td></tr>';
 const cs=s.chain_subscriber||{};$('autoChain').innerHTML=!cs.enabled?'<span class="muted">Off. Set KOTAK_AUTO_CHAIN_JSON to keep strikes around spot subscribed.</span>':metric('Subscribed tokens',cs.subscribed??0)+metric('Open positions kept',cs.positions??0)+(cs.capped?metric('Cap reached','YES','warn'):'')+(cs.error?metric('Error',cs.error,'bad'):'')+Object.entries(cs.underlyings||{}).map(([u,i])=>metric(u,i.status!=='OK'?i.status:['LIVE_SPOT','PUT_CALL_PARITY','SPOT_TOKEN'].includes(i.spot_source)?`ATM ${Object.values(i.atm||{}).map(fmt).join(' / ')} · ${i.tokens} tokens · ${i.spot_source}`:`${i.tokens} tokens · window centred on ${i.spot_source==='MEDIAN_STRIKE'?'the median listed strike':'the last (stale) spot'}: no live spot`,i.status==='OK'&&['LIVE_SPOT','PUT_CALL_PARITY','SPOT_TOKEN'].includes(i.spot_source)?'':'warn')).join('');
 $('riskLimits').innerHTML=Object.entries(s.risk?.limits||{}).map(([a,b])=>metric(a,fmt(b))).join('');
 const maxAge=s.risk?.snapshot_max_age_sec;
 $('riskSnaps').innerHTML=Object.values(s.risk?.snapshots||{}).map(x=>{const fresh=maxAge==null||x.age_sec<=maxAge,use=x.ok&&fresh;return`<div class="metric"><span><b>${esc(x.broker)}</b> ${use?'<span class="ok">LIVE</span>':x.ok?'<span class="warn">STALE</span>':'<span class="bad">NOT USABLE</span>'} · age ${esc(x.age_sec)}s</span><span>${use?`P&amp;L ${fmt(x.total_pnl)} · day ${fmt(x.day_pnl)} (${esc(x.day_pnl_source||'—')}) · margin ${x.margin?fmt(x.margin.pct)+'%':'—'} · exposure ${fmt(x.premium_exposure)} · short notional ${fmt(x.short_option_notional)}`:'No live broker data'}</span></div>${(x.issues||[]).length||x.error?`<div class="muted bad">${esc([x.error,...(x.issues||[])].filter(Boolean).join(' · '))}</div>`:''}`}).join('')||'<span class="muted">No live broker data: no broker snapshot yet.</span>';
 const c=s.controls||{};$('ctlList').innerHTML=Object.entries(c).map(([a,b])=>metric(a.replaceAll('_',' '),b===true?'ON':b===false?'OFF':b,b===false?'warn':'')).join('');
 $('aiInfo').innerHTML=metric('Gate mode',c.ai_gate_mode)+metric('Auto trading',sys.auto_trading?'ON':'OFF')+metric('Human approval for AUTO',s.execution?.approval_required?'REQUIRED':'NOT REQUIRED');
 $('orderRows').innerHTML=(s.orders||[]).map(o=>`<tr><td>${esc(o.created_at?istTime(/[zZ]|[+-]\d\d:?\d\d$/.test(o.created_at)?o.created_at:o.created_at+'Z'):'—')}</td><td>${esc(o.client_order_id)}</td><td>${esc(o.broker)}</td><td>${esc(o.broker_order_id)}</td><td>${esc(o.symbol)}</td><td>${esc(o.side)}</td><td>${esc(o.qty)}</td><td>${esc(o.filled_qty)}</td><td>${esc(o.status)}</td><td>${o.avg_price>0?esc(o.avg_price):"—"}</td><td>${esc(o.origin)}</td><td>${esc(o.last_reason)}</td><td>${['SUBMITTED','OPEN','PARTIAL'].includes(o.status)&&o.broker_order_id?`<button class="linkbtn" type="button" data-action="cancel-order" data-cid="${esc(o.client_order_id)}">Cancel</button>`:''}</td></tr>`).join('')||'<tr><td colspan="13" class="muted">No orders.</td></tr>';
 const conf=(s.brokers||[]).filter(b=>b.status!=='UNCONFIGURED').map(b=>[b.broker,b.broker]);if(conf.length)setOptions($('esBroker'),conf,conf.some(c=>c[0]===$('esBroker').value)?$('esBroker').value:conf[0][0]);
 $('reconRows').innerHTML=Object.entries(s.reconciliation||{}).map(([b,r])=>!r?`<tr><td>${esc(b)}</td><td class="warn">NEVER RUN</td><td>—</td><td>—</td><td></td></tr>`:`<tr><td>${esc(b)}</td><td class="${r.ok?'ok':'bad'}">${r.ok?'MATCHED':'MISMATCH'}</td><td>${esc(Math.round(r.age_sec))}s</td><td>${esc((r.mismatches||[]).length)}</td><td class="wrap muted">${esc((r.mismatches||[]).slice(0,3).map(m=>typeof m==='string'?m:JSON.stringify(m)).join(' · '))}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No configured brokers.</td></tr>';
 $('ledgerMetrics').innerHTML=Object.entries(s.ledger||{}).map(([k,v])=>metric(k.replaceAll('_',' '),fmt(v))).join('');
 $('tcaRows').innerHTML=(s.tca||[]).map(x=>`<tr><td>${esc(x.client_order_id)}</td><td>${esc(x.side)}</td><td>${esc(x.arrival)}</td><td>${esc(x.avg_fill)}</td><td class="${x.slippage_bps>0?'bad':'ok'}">${esc(x.slippage_bps)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No fills yet</td></tr>';
 const eb=sys.event_bus||{};$('taskHealth').innerHTML=Object.entries(sys.tasks||{}).map(([n,h])=>metric(n,h.running?(h.restarts?`RUNNING · restarted ${h.restarts}×`:'RUNNING'):`RESTARTING${h.last_error?' · '+h.last_error:''}`,h.running?(h.restarts?'warn':'ok'):'bad')).join('')+(eb.required?metric('Redis (durable events)',eb.connected?(eb.reconnects?`CONNECTED · reconnected ${eb.reconnects}×`:'CONNECTED'):'RECONNECTING'+(eb.last_error?' · '+eb.last_error:''),eb.connected?'ok':'bad'):'')||'<span class="muted">Background loops start with the terminal.</span>';
 $('sysMetrics').innerHTML=metric('Market',sys.market,sys.market==='LIVE'?'ok':'bad')+metric('Watchdog',sys.watchdog?'HEALTHY':'TRIPPED',sys.watchdog?'ok':'bad')+metric('Durable event bus',sys.durable_event_bus?'CONNECTED':'NOT CONNECTED',sys.durable_event_bus?'ok':'warn')+metric('Event queue depth',sys.event_queue_depth)+metric('Order monitor',sys.order_monitor?.running?'RUNNING':'STOPPED',sys.order_monitor?.running?'ok':'bad')+metric('Risk monitor last run',sys.risk_monitor?.last_eval?new Date(sys.risk_monitor.last_eval.at*1000).toLocaleTimeString():'—')+metric('Order routing',sys.live_trading?'LIVE':'LOCKED',sys.live_trading?'warn':'')+metric('Auto trading',sys.auto_trading?'ON':'OFF');
 const il=s.instrument_loader||{};$('auditMetrics').innerHTML=metric('Audit records',fmt(s.audit?.records))+metric('Latest hash',s.audit?.latest_hash?s.audit.latest_hash.slice(0,16)+'…':'—')+metric('Kotak master auto-load',il.enabled?(il.fresh_today?'TODAY\'S FILES':il.last_error?'RETRY IN '+il.retry_in_sec+'s':'WAITING'):'OFF',il.enabled?(il.fresh_today?'ok':'warn'):'')+(il.last_error?`<div class="muted bad wrap">${esc(il.last_error)}</div>`:'')+Object.entries(s.static_instrument_refresh||{}).map(([b,r])=>metric(b+' master refresh',r.last_error?'RETRY IN '+r.retry_in_sec+'s':r.loaded?'LOADED':'PENDING',r.last_error?'warn':'')).join('');
 $('instRows').innerHTML=Object.entries(s.instruments||{}).map(([b,i])=>`<tr><td>${esc(b)}</td><td>${fmt(i.count)}</td><td>${esc(i.source_date||'—')}</td><td>${yn(i.fresh_today)}</td><td>${i.loaded_at?esc(new Date(i.loaded_at*1000).toLocaleString('en-IN')):'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No instrument master loaded.</td></tr>';
 $('systemState').textContent=JSON.stringify(sys,null,2);$('auditState').textContent=JSON.stringify({audit:s.audit,instruments:s.instruments,instrument_loader:s.instrument_loader,chain_subscriber:s.chain_subscriber},null,2);
 window.dispatchEvent(new CustomEvent('iort:state',{detail:s}))}
// Backend unreachable: blank every panel. Nothing from the last good poll may stay on screen as if live.
function renderUnavailable(why){LAST={};const none=`<span class="muted">No live data: ${esc(why)}</span>`,row=n=>`<tr><td colspan="${n}" class="muted">No live data: ${esc(why)}</td></tr>`;
 $('conn').textContent='BACKEND UNAVAILABLE';cls($('conn'),'bad');for(const id of['marketPill','ovMarket']){$(id).textContent='DATA UNAVAILABLE';cls($(id),'bad')}
 for(const[id,v]of[['ovPnl','—'],['ovReadyFlag','—'],['ovExec','—'],['riskKill','—'],['modePill','ORDERS —'],['killPill','KILL: —'],['streamPill','FEED —'],['latPill','LATENCY —']]){$(id).textContent=v;cls($(id),'')}
 $('riskKillWhy').textContent='';$('ovReady').textContent='Unknown: '+why;
 for(const id of['ovBrokers','marketQuality','autoChain','riskSnaps','riskLimits','ledgerMetrics','sysMetrics','auditMetrics','taskHealth','ctlList','aiInfo'])$(id).innerHTML=none;
 for(const[id,n]of[['excRows',7],['marketRows',9],['workerRows',10],['chainRows',5],['orderRows',13],['reconRows',5],['tcaRows',5],['instRows',5]])$(id).innerHTML=row(n);
 window.dispatchEvent(new CustomEvent('iort:state',{detail:null}))}
async function refresh(){if(refreshing)return;refreshing=true;
 try{const r=await fetchT('/dashboard/state');if(!r.ok)throw new Error('HTTP '+r.status);const s=await r.json();lastOk=Date.now();render(s)}
 catch(e){renderUnavailable(e.name==='AbortError'?'the backend did not answer within 2.5 s':'the backend is not reachable ('+(e.message||'error')+')')}
 finally{refreshing=false}}
// Watchdog: a hung backend (no answer at all) also blanks the panels after 7 s.
setInterval(()=>{if(lastOk&&Date.now()-lastOk>7000&&$('conn').textContent!=='BACKEND UNAVAILABLE')renderUnavailable('no answer for 7 s')},1000);
const ROUTE={riskEvents:['KILL_SWITCH','KILL_SWITCH_RESET','RISK_BLOCK','RISK_ALERT'],executionEvents:['ORDER_SUBMISSION','ORDER_UPDATE','FILL','EMERGENCY_STOP','CONTROL_RESULT'],reconEvents:['RECONCILIATION']};
function connectWS(){if(ws&&ws.readyState<2)return;clearTimeout(reconnectTimer);ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/events');
 ws.onopen=()=>{wsDelay=500;wsLastMsg=Date.now();if(lastOk)connPill();refresh()};
 ws.onmessage=ev=>{wsLastMsg=Date.now();let e;try{e=JSON.parse(ev.data)}catch{return}window.dispatchEvent(new CustomEvent('iort:event',{detail:e}));
  if(e.type==='HEARTBEAT'||e.type==='STATE'){const m=e.market||'DATA_UNAVAILABLE',ok=m==='LIVE';for(const id of['marketPill','ovMarket']){$(id).textContent=m;cls($(id),ok?'ok':'bad')}return}
  if(e.type==='MARKET_TICK')return;logEvent('ovEvents',e);for(const[id,types]of Object.entries(ROUTE))if(types.includes(e.type))logEvent(id,e);if(['KILL_SWITCH','KILL_SWITCH_RESET','ORDER_SUBMISSION','ORDER_UPDATE','FILL','RECONCILIATION','EMERGENCY_STOP','STREAM_CONNECTED','STREAM_DISCONNECTED','STREAM_ERROR','STREAM_RECONNECTING'].includes(e.type))refresh()};
 ws.onclose=()=>{if(lastOk&&$('conn').textContent!=='BACKEND UNAVAILABLE')connPill();clearTimeout(reconnectTimer);
  // Reconnect with backoff and jitter: 0.5, 1, 2, 5, 10 s.
  reconnectTimer=setTimeout(connectWS,wsDelay+Math.random()*250);wsDelay=Math.min(wsDelay*2,10000)};ws.onerror=()=>{try{ws.close()}catch{}}}
// The server sends a heartbeat every 2 s: an open socket silent for 8 s is half-open (sleep, NAT, proxy), so drop it.
setInterval(()=>{if(ws&&ws.readyState===1&&Date.now()-wsLastMsg>8000){try{ws.close()}catch{}}},2000);
const wakeUp=()=>{wsDelay=500;if(!ws||ws.readyState>1)connectWS();refresh()};
window.addEventListener('online',wakeUp);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')wakeUp()});
async function control(url,tries=1){const token=$('op').value.trim();if(!token){alert('Operator token required (Execution tab)');return}
 for(let i=0;i<tries;i++){try{const r=await fetch(url,{method:'POST',headers:{'X-IORT-Operator-Token':token}});let j;try{j=await r.json()}catch{j={http:r.status}}
   logEvent('executionEvents',{type:'CONTROL_RESULT',payload:j});if(!r.ok)toast(`${url.split('?')[0]}: ${j.reason||j.status||'HTTP '+r.status}`,'bad');await refresh();return j}
  catch{if(i+1<tries){await new Promise(res=>setTimeout(res,1000*(i+1)));continue}
   logEvent('executionEvents',{type:'CONTROL_RESULT',payload:{status:'NO_RESPONSE',url}});toast('Control NOT delivered: the backend is unreachable','bad');return null}}}
const panic=async()=>{if(await control('/kill?reason=UI_PANIC',3)===null)alert('PANIC was NOT delivered: the backend is unreachable. Use the broker\'s own terminal to stop trading.')}; // kill is idempotent, so it is retried
function resetKill(){const why=$('resetWhy').value.trim();if(why.length<3){alert('Give a reset reason');return}if(confirm('Reset the kill switch? New orders become possible again.'))control('/kill/reset?reason='+encodeURIComponent(why))}
function emergency(){const b=$('esBroker').value,f=$('esFlatten').checked;if(confirm(`Emergency stop ${b}${f?' AND FLATTEN ALL POSITIONS':''}?`))control(`/emergency-stop/${b}?flatten=${f}`)}
const reconcileNow=()=>control('/reconcile/'+$('esBroker').value);
const reconnectFeed=b=>control(`/brokers/${encodeURIComponent(b)}/reconnect`);
function loginReset(b){if(confirm(`Reset the ${b} login halt? The terminal will try to log in again with the configured credentials.`))control(`/brokers/${b}/login-reset`)}
// One delegated listener for every [data-action] button: no inline handlers, so the
// Content-Security-Policy can forbid inline script entirely.
const ACTIONS={panic,'reset-kill':resetKill,emergency,reconcile:reconcileNow,'login-reset':el=>loginReset(el.dataset.broker),
 reconnect:el=>reconnectFeed(el.dataset.broker),
 'auto-reconnect':el=>{const on=el.dataset.on==='true';if(on||confirm(`Turn automatic reconnect OFF for ${el.dataset.broker}? A dropped feed will then stay down until you press Reconnect now.`))control(`/brokers/${encodeURIComponent(el.dataset.broker)}/auto-reconnect?enabled=${on}`)},
 'open-chain':el=>openChain(el.dataset.sym,el.dataset.exp),'close-overlay':()=>closeOverlays(),
 'cancel-order':el=>{if(confirm(`Cancel order ${el.dataset.cid} at the broker?`))control(`/orders/${encodeURIComponent(el.dataset.cid)}/cancel`)}};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||!ACTIONS[el.dataset.action])return;e.preventDefault();ACTIONS[el.dataset.action](el)});
// Machine diagnostics (System tab): GET /ops/doctor. Read-only; no credential value is ever returned.
async function runDoctor(){const b=$('docRun');b.disabled=true;$('docOut').innerHTML='<p class="muted">Running checks (up to about 10 s)…</p>';
 try{const r=await fetch('/ops/doctor',{cache:'no-store'});const d=await r.json();const C={OK:'ok',INFO:'',WARN:'warn',FAIL:'bad'};
  $('docOut').innerHTML=`<p><span class="badge ${C[d.summary]}">${esc(d.summary)}</span> <span class="muted">${esc(d.took_sec)} s</span></p><div class="tw"><table><thead><tr><th>Area</th><th>Check</th><th>Result</th><th>Detail</th><th>How to fix</th></tr></thead><tbody>${d.checks.map(c=>`<tr><td>${esc(c.group)}</td><td>${esc(c.name)}</td><td class="${C[c.status]}">${esc(c.status)}</td><td class="wrap">${esc(c.detail)}</td><td class="wrap muted">${esc(c.status==='WARN'||c.status==='FAIL'?c.fix||'':'')}</td></tr>`).join('')}</tbody></table></div>`}
 catch{$('docOut').innerHTML='<p class="bad">Diagnostics unavailable: the backend is not reachable.</p>'}finally{b.disabled=false}}
$('docRun').addEventListener('click',runDoctor);
