"use strict";
// Core: helpers, tabs, dashboard rendering, event stream and operator controls.
const TABS=[['overview','Overview'],['market','Market'],['chain','Option Chain'],['portfolio','Portfolio'],['strategy','Strategy'],['risk','Risk'],['controls','Controls'],['execution','Execution'],['orders','Orders'],['recon','Reconciliation'],['tca','TCA'],['system','System']];
let ws=null,reconnectTimer=null;const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const cls=(el,c)=>{el.className=el.className.replace(/\b(ok|bad|warn)\b/g,'').trim()+' '+c};
function initTabs(){TABS.forEach(([id,label],i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.tab=id;b.setAttribute('role','tab');b.setAttribute('aria-controls',id);b.title=i<9?`${label} (Alt+${i+1})`:label;b.onclick=()=>showTab(id);$('tabs').appendChild(b)});
 let start=(location.hash||'').slice(1);if(!TABS.some(t=>t[0]===start)){try{start=localStorage.getItem('iort.tab')||''}catch{start=''}}
 showTab(TABS.some(t=>t[0]===start)?start:TABS[0][0])}
function showTab(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>{x.classList.toggle('active',x.dataset.tab===id);x.setAttribute('aria-selected',x.dataset.tab===id)});
 try{localStorage.setItem('iort.tab',id)}catch{}if(location.hash!=='#'+id)history.replaceState(null,'','#'+id);
 CH.active=id==='chain';if(CH.active){CH.scroll=true;chLoadIndex().then(chLoadLadder)}
 window.dispatchEvent(new CustomEvent('iort:tab',{detail:id}))}
function logEvent(target,e){const el=$(target);if(!el)return;const row=document.createElement('div');row.className='event';row.textContent=new Date().toLocaleTimeString()+'  '+(e.type||'EVENT')+'  '+JSON.stringify(e.payload||e);el.prepend(row);while(el.children.length>100)el.removeChild(el.lastChild)}
const yn=v=>v?'<span class="ok">YES</span>':'<span class="bad">NO</span>';
const metric=(k,v,c='')=>`<div class="metric"><span>${esc(k)}</span><b class="${c}">${esc(v)}</b></div>`;
function render(s){const sys=s.system||{};$('ver').textContent='v'+(s.version||'');
 const live=sys.market==='LIVE';$('ovMarket').textContent=sys.market||'DATA_UNAVAILABLE';cls($('ovMarket'),live?'ok':'bad');$('marketPill').textContent=sys.market||'DATA_UNAVAILABLE';cls($('marketPill'),live?'ok':'bad');
 $('ovExec').textContent=sys.live_trading?'LIVE ENABLED':'DISABLED';cls($('ovExec'),sys.live_trading?'warn':'bad');$('modePill').textContent=sys.live_trading?'LIVE':'PAPER';cls($('modePill'),sys.live_trading?'warn':'ok');
 const k=sys.kill||{};$('killPill').textContent='KILL: '+(k.active?'ON':'OFF');cls($('killPill'),k.active?'bad':'ok');$('riskKill').textContent=k.active?'ACTIVE':'OFF';cls($('riskKill'),k.active?'bad':'ok');$('riskKillWhy').textContent=k.reason?`${k.reason} · ${k.actor||''} · ${k.at||''}`:'';
 $('conn').textContent='CONNECTED';cls($('conn'),'ok');
 const agg=(s.risk||{}).aggregate||{};$('ovPnl').textContent=`${fmt(agg.total_pnl)} / ${fmt(agg.day_pnl)}`;cls($('ovPnl'),(agg.total_pnl||0)<0?'bad':'ok');
 const rd=s.readiness||{};$('ovReadyFlag').textContent=rd.ready?'READY':'BLOCKED';cls($('ovReadyFlag'),rd.ready?'ok':'bad');$('ovReady').textContent=(rd.reasons||[]).join('\n')||'none';
 $('ovBrokers').innerHTML=(s.brokers||[]).map(b=>metric(b.broker,b.status||'UNKNOWN',b.status==='LIVE'?'ok':b.status==='UNCONFIGURED'?'':'bad')
  +(b.error?`<div class="muted bad">${esc(b.error)}</div>`:'')+(b.status==='LOGIN_HALTED'?`<div class="control" style="margin:6px 0"><button class="action amber" data-action="login-reset" data-broker="${esc(b.broker)}">Reset ${esc(b.broker)} login</button><span class="muted">Fix the credentials first. Needs the operator token from the Execution tab.</span></div>`:'')).join('')||'<span class="muted">No broker data</span>';
 $('excRows').innerHTML=(s.exceptions||[]).map(o=>`<tr><td>${esc(o.client_order_id)}</td><td>${esc(o.broker)}</td><td>${esc(o.symbol)}</td><td>${esc(o.side)}</td><td>${esc(o.qty)}</td><td class="bad">${esc(o.status)}</td><td>${esc(o.last_reason)}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">None</td></tr>';
 $('marketRows').innerHTML=(s.market?.last_ticks||[]).map(t=>`<tr><td>${esc(t.broker)}</td><td>${esc(t.instrument_token)}</td><td>${esc(t.exchange)}</td><td>${esc(t.symbol)}</td><td>${esc(t.ltp)}</td><td>${esc(t.bid)}</td><td>${esc(t.ask)}</td><td>${esc(t.oi)}</td><td>${t.exchange_ts_ms?esc(new Date(t.exchange_ts_ms).toLocaleTimeString()):'—'}</td></tr>`).join('');
 const st=s.market?.stats||{};$('marketQuality').innerHTML=metric('Accepted ticks',st.accepted??0)+Object.entries(st.rejected_by_reason||{}).map(([r,n])=>metric('Rejected: '+r,n,'warn')).join('')+metric('Live brokers',(st.live_brokers||[]).join(', ')||'none');
 $('workerRows').innerHTML=(sys.workers||[]).map(w=>`<tr><td>${esc(w.broker)}</td><td>${yn(w.running)}</td><td>${yn(w.healthy)}</td><td>${esc(w.reconnects)}</td><td>${esc(w.dropped)}</td><td>${esc(w.dynamic_tokens??0)}</td><td class="wrap ${w.last_error?'bad':''}">${esc(w.last_error||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">No stream workers: no broker feed is configured.</td></tr>';
 $('chainRows').innerHTML=(s.option_chain?.chains||[]).slice().sort((a,b)=>(a.underlying+a.expiry).localeCompare(b.underlying+b.expiry)).map(c=>`<tr><td>${esc(c.exchange)}</td><td><b>${esc(c.underlying)}</b></td><td>${esc(c.expiry)}</td><td>${esc(c.rows)}</td><td><button class="linkbtn" type="button" data-action="open-chain" data-sym="${esc(c.exchange+'|'+c.underlying)}" data-exp="${esc(c.expiry)}">Open chain</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No option ticks yet.</td></tr>';
 const cs=s.chain_subscriber||{};$('autoChain').innerHTML=!cs.enabled?'<span class="muted">Off. Set KOTAK_AUTO_CHAIN_JSON to keep strikes around spot subscribed.</span>':metric('Subscribed tokens',cs.subscribed??0)+metric('Open positions kept',cs.positions??0)+(cs.capped?metric('Cap reached','YES','warn'):'')+(cs.error?metric('Error',cs.error,'bad'):'')+Object.entries(cs.underlyings||{}).map(([u,i])=>metric(u,i.status==='OK'?`ATM ${Object.values(i.atm||{}).map(fmt).join(' / ')} · ${i.tokens} tokens · ${i.spot_source}`:i.status,i.status==='OK'?'':'warn')).join('');
 $('riskLimits').innerHTML=Object.entries(s.risk?.limits||{}).map(([a,b])=>metric(a,fmt(b))).join('');
 $('riskSnaps').innerHTML=Object.values(s.risk?.snapshots||{}).map(x=>`<div class="metric"><span><b>${esc(x.broker)}</b> ${x.ok?'<span class="ok">OK</span>':'<span class="bad">NOT USABLE</span>'} · age ${esc(x.age_sec)}s</span><span>P&amp;L ${fmt(x.total_pnl)} · day ${fmt(x.day_pnl)} (${esc(x.day_pnl_source||'—')}) · margin ${x.margin?fmt(x.margin.pct)+'%':'—'} · exposure ${fmt(x.premium_exposure)} · short notional ${fmt(x.short_option_notional)}</span></div>${(x.issues||[]).length||x.error?`<div class="muted bad">${esc([x.error,...(x.issues||[])].filter(Boolean).join(' · '))}</div>`:''}`).join('')||'<span class="muted">No configured broker snapshots</span>';
 const c=s.controls||{};$('ctlList').innerHTML=Object.entries(c).map(([a,b])=>metric(a.replaceAll('_',' '),b===true?'ON':b===false?'OFF':b,b===false?'warn':'')).join('');
 $('aiInfo').innerHTML=metric('Gate mode',c.ai_gate_mode)+metric('Auto trading',sys.auto_trading?'ON':'OFF')+metric('Human approval for AUTO',s.execution?.approval_required?'REQUIRED':'NOT REQUIRED');
 $('orderRows').innerHTML=(s.orders||[]).map(o=>`<tr><td>${esc((o.created_at||'').slice(11,19))}</td><td>${esc(o.client_order_id)}</td><td>${esc(o.broker)}</td><td>${esc(o.broker_order_id)}</td><td>${esc(o.symbol)}</td><td>${esc(o.side)}</td><td>${esc(o.qty)}</td><td>${esc(o.filled_qty)}</td><td>${esc(o.status)}</td><td>${esc(o.avg_price)}</td><td>${esc(o.origin)}</td><td>${esc(o.last_reason)}</td></tr>`).join('');
 $('reconRows').innerHTML=Object.entries(s.reconciliation||{}).map(([b,r])=>!r?`<tr><td>${esc(b)}</td><td class="warn">NEVER RUN</td><td>—</td><td>—</td><td></td></tr>`:`<tr><td>${esc(b)}</td><td class="${r.ok?'ok':'bad'}">${r.ok?'MATCHED':'MISMATCH'}</td><td>${esc(Math.round(r.age_sec))}s</td><td>${esc((r.mismatches||[]).length)}</td><td class="wrap muted">${esc((r.mismatches||[]).slice(0,3).map(m=>typeof m==='string'?m:JSON.stringify(m)).join(' · '))}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No configured brokers.</td></tr>';
 $('ledgerMetrics').innerHTML=Object.entries(s.ledger||{}).map(([k,v])=>metric(k.replaceAll('_',' '),fmt(v))).join('');
 $('tcaRows').innerHTML=(s.tca||[]).map(x=>`<tr><td>${esc(x.client_order_id)}</td><td>${esc(x.side)}</td><td>${esc(x.arrival)}</td><td>${esc(x.avg_fill)}</td><td class="${x.slippage_bps>0?'bad':'ok'}">${esc(x.slippage_bps)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No fills yet</td></tr>';
 $('sysMetrics').innerHTML=metric('Market',sys.market,sys.market==='LIVE'?'ok':'bad')+metric('Watchdog',sys.watchdog?'HEALTHY':'TRIPPED',sys.watchdog?'ok':'bad')+metric('Durable event bus',sys.durable_event_bus?'CONNECTED':'NOT CONNECTED',sys.durable_event_bus?'ok':'warn')+metric('Event queue depth',sys.event_queue_depth)+metric('Order monitor',sys.order_monitor?.running?'RUNNING':'STOPPED',sys.order_monitor?.running?'ok':'bad')+metric('Risk monitor last run',sys.risk_monitor?.last_eval?new Date(sys.risk_monitor.last_eval.at*1000).toLocaleTimeString():'—')+metric('Live trading',sys.live_trading?'ON':'OFF',sys.live_trading?'warn':'ok')+metric('Auto trading',sys.auto_trading?'ON':'OFF');
 const il=s.instrument_loader||{};$('auditMetrics').innerHTML=metric('Audit records',fmt(s.audit?.records))+metric('Latest hash',s.audit?.latest_hash?s.audit.latest_hash.slice(0,16)+'…':'—')+metric('Kotak master auto-load',il.enabled?(il.fresh_today?'TODAY\'S FILES':il.last_error?'RETRY IN '+il.retry_in_sec+'s':'WAITING'):'OFF',il.enabled?(il.fresh_today?'ok':'warn'):'')+(il.last_error?`<div class="muted bad wrap">${esc(il.last_error)}</div>`:'')+Object.entries(s.static_instrument_refresh||{}).map(([b,r])=>metric(b+' master refresh',r.last_error?'RETRY IN '+r.retry_in_sec+'s':r.loaded?'LOADED':'PENDING',r.last_error?'warn':'')).join('');
 $('instRows').innerHTML=Object.entries(s.instruments||{}).map(([b,i])=>`<tr><td>${esc(b)}</td><td>${fmt(i.count)}</td><td>${esc(i.source_date||'—')}</td><td>${yn(i.fresh_today)}</td><td>${i.loaded_at?esc(new Date(i.loaded_at*1000).toLocaleString('en-IN')):'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No instrument master loaded.</td></tr>';
 $('systemState').textContent=JSON.stringify(sys,null,2);$('auditState').textContent=JSON.stringify({audit:s.audit,instruments:s.instruments,instrument_loader:s.instrument_loader,chain_subscriber:s.chain_subscriber},null,2);
 window.dispatchEvent(new CustomEvent('iort:state',{detail:s}))}
async function refresh(){try{const r=await fetch('/dashboard/state',{cache:'no-store'});if(!r.ok)throw new Error(r.status);render(await r.json())}catch(e){$('conn').textContent='BACKEND UNAVAILABLE';cls($('conn'),'bad');$('marketPill').textContent='DATA UNAVAILABLE';cls($('marketPill'),'bad')}}
const ROUTE={riskEvents:['KILL_SWITCH','KILL_SWITCH_RESET','RISK_BLOCK','RISK_ALERT'],executionEvents:['ORDER_SUBMISSION','ORDER_UPDATE','FILL','EMERGENCY_STOP','CONTROL_RESULT'],reconEvents:['RECONCILIATION']};
function connectWS(){if(ws&&ws.readyState<2)return;ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/events');
 ws.onopen=()=>{$('conn').textContent='EVENT STREAM';cls($('conn'),'ok')};
 ws.onmessage=ev=>{let e;try{e=JSON.parse(ev.data)}catch{return}window.dispatchEvent(new CustomEvent('iort:event',{detail:e}));if(e.type==='MARKET_TICK'||e.type==='HEARTBEAT')return;logEvent('ovEvents',e);for(const[id,types]of Object.entries(ROUTE))if(types.includes(e.type))logEvent(id,e);if(['KILL_SWITCH','KILL_SWITCH_RESET','ORDER_SUBMISSION','ORDER_UPDATE','FILL','RECONCILIATION','EMERGENCY_STOP'].includes(e.type))refresh()};
 ws.onclose=()=>{$('conn').textContent='RECONNECTING';cls($('conn'),'warn');clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connectWS,1500)};ws.onerror=()=>{try{ws.close()}catch{}}}
async function control(url){const token=$('op').value.trim();if(!token){alert('Operator token required');return}const r=await fetch(url,{method:'POST',headers:{'X-IORT-Operator-Token':token}});let j;try{j=await r.json()}catch{j={http:r.status}}logEvent('executionEvents',{type:'CONTROL_RESULT',payload:j});await refresh()}
const panic=()=>control('/kill?reason=UI_PANIC');
function resetKill(){const why=$('resetWhy').value.trim();if(why.length<3){alert('Give a reset reason');return}if(confirm('Reset the kill switch? New orders become possible again.'))control('/kill/reset?reason='+encodeURIComponent(why))}
function emergency(){const b=$('esBroker').value,f=$('esFlatten').checked;if(confirm(`Emergency stop ${b}${f?' AND FLATTEN ALL POSITIONS':''}?`))control(`/emergency-stop/${b}?flatten=${f}`)}
const reconcileNow=()=>control('/reconcile/'+$('esBroker').value);
function loginReset(b){if(confirm(`Reset the ${b} login halt? The terminal will try to log in again with the configured credentials.`))control(`/brokers/${b}/login-reset`)}
// One delegated listener for every [data-action] button: no inline handlers, so the
// Content-Security-Policy can forbid inline script entirely.
const ACTIONS={panic,'reset-kill':resetKill,emergency,reconcile:reconcileNow,'login-reset':el=>loginReset(el.dataset.broker),
 'open-chain':el=>openChain(el.dataset.sym,el.dataset.exp),'close-overlay':()=>closeOverlays()};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||!ACTIONS[el.dataset.action])return;e.preventDefault();ACTIONS[el.dataset.action](el)});
